# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 18:28
from __future__ import unicode_literals

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('profile_picture', models.URLField(blank=True, null=True, verbose_name='Profile picture')),
                ('deactivated_until', models.DateTimeField(blank=True, null=True)),
                ('third_party_login', models.CharField(blank=True, max_length=32, null=True)),
                ('url_slug', models.SlugField(blank=True, help_text='This will be a part of the address of your public page                                     and cannot be changed later.', null=True, unique=True, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(16)], verbose_name='URL slug')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Developer website')),
                ('support_email', models.EmailField(blank=True, help_text='Visible to those users that have bought your games', max_length=254, null=True, verbose_name='Developer support email')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
