# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 19:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=50, unique=True, verbose_name='Display name')),
                ('profile_picture', models.URLField(blank=True, null=True, verbose_name='Profile picture')),
                ('deactivated_until', models.DateTimeField(blank=True, null=True)),
                ('third_party_login', models.CharField(blank=True, max_length=32, null=True)),
                ('url_slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='URL slug')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Developer website')),
                ('support_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Developer support email')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
