# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 12:13
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='support_email',
            field=models.EmailField(blank=True, help_text='Visible to those users that have bought your games', max_length=254, null=True, verbose_name='Developer support email'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='url_slug',
            field=models.SlugField(blank=True, help_text='This will be a part of the address of your public page                                     and cannot be changed later.', null=True, unique=True, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(16)], verbose_name='URL slug'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
