# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20161229_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dev_slug',
            field=models.SlugField(default='asd', unique=True),
            preserve_default=False,
        ),
    ]
