# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170109_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='dev_slug',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dev_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
