# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 07:42
from __future__ import unicode_literals

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20170109_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Display Name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dev_email_support',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Developer Support Email'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dev_website',
            field=models.URLField(blank=True, null=True, verbose_name='Developer Website'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=users.models.get_upload_path, verbose_name='Profile Picture'),
        ),
    ]
