# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20170110_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperProfile',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.UserProfile')),
                ('url_slug', models.SlugField(unique=True, verbose_name='URL slug')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Developer website')),
                ('support_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Developer support email')),
            ],
            bases=('users.userprofile',),
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.UserProfile')),
            ],
            bases=('users.userprofile',),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='dev_email_support',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='dev_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='dev_website',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Display name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=users.models.get_upload_path, verbose_name='Profile picture'),
        ),
    ]
