# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20161229_0220'),
        ('transactions', '0001_initial'),
        ('users', '0014_auto_20170110_1253'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeveloperProfile',
        ),
        migrations.DeleteModel(
            name='PlayerProfile',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='support_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Developer support email'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='url_slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='URL slug'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Developer website'),
        ),

    ]
