# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 17:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deactivated_until', models.DateTimeField(blank=True, null=True)),
                ('profile_pic', models.ImageField(upload_to='')),
                ('third_party_login', models.CharField(blank=True, max_length=32, null=True)),
                ('dev_slug', models.SlugField(blank=True, null=True)),
                ('dev_website', models.URLField(blank=True, null=True)),
                ('dev_email_support', models.EmailField(blank=True, max_length=254, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
