# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 02:20
from __future__ import unicode_literals

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=users.models.get_upload_path),
        ),
    ]
