# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170109_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dev_slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
