# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170109_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dev_slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
