# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20170110_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(default='asd', max_length=50, unique=True, verbose_name='Display Name'),
            preserve_default=False,
        ),
    ]
