# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20170110_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(max_length=50, verbose_name='Display Name'),
        ),
    ]
