# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 09:03
from __future__ import unicode_literals

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20170110_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(default=builtins.id, max_length=50, verbose_name='Display Name'),
        ),
    ]
