# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_ref',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
