# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 18:28
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Game name')),
                ('slug', models.SlugField(help_text='Part of the game page address on LevelUp, cannot be changed later', unique=True, verbose_name='Game URL slug')),
                ('url', models.URLField(help_text='Where is the game hosted?', verbose_name='Source URL')),
                ('icon', models.URLField(blank=True, null=True)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('is_public', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('dev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='users.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='GameScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='games.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='users.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='GameScreenshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='games.Game')),
            ],
        ),
    ]
