# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Game name'),
        ),
        migrations.AlterField(
            model_name='game',
            name='slug',
            field=models.SlugField(help_text='Part of the game page address on LevelUp, cannot be changed later', unique=True, verbose_name='Game URL slug'),
        ),
        migrations.AlterField(
            model_name='game',
            name='url',
            field=models.URLField(help_text='Where is the game hosted?', verbose_name='Source URL'),
        ),
    ]
