# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 00:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import games.models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='icon',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=games.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='gamescreenshot',
            name='image',
            field=models.ImageField(max_length=255, upload_to=games.models.get_upload_path),
        ),
    ]
