# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20170122_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200)),
            ],
        ),
    ]
