# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 20:12
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_gamesearch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameSearch',
        ),
        migrations.AlterField(
            model_name='game',
            name='icon',
            field=cloudinary.models.CloudinaryField(default='image/upload/v1485195482/default/thug.jpg', max_length=255, verbose_name='Game icon'),
        ),
        migrations.AlterField(
            model_name='gamescreenshot',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Screen shot'),
        ),
    ]
