# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-02 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20170123_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='category',
            field=models.CharField(choices=[('action', 'Action'), ('adventure', 'Adventure'), ('arcade', 'Arcade'), ('kids', 'Kids'), ('rpg', 'RPG'), ('sport', 'Sport'), ('strategy', 'Strategy')], default='action', max_length=31),
            preserve_default=False,
        ),
    ]
