# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-03 11:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_game_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamescore',
            old_name='start_time',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='gamescore',
            name='end_time',
        ),
    ]
