# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-10 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_game_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(db_index=True, max_length=64, verbose_name='Game name'),
        ),
    ]
